### ISSUE TITLE
Still Maintained?

### ISSUE THREAD

**Issue by helgetan** [webcat12345/ngx-intl-tel-input#133]
Hey is this repo still maintained?
@webcat12345 

maybe we could share the maintenance or work something out;)

**Comment by webcat12345** [comment]
@helgetan if you can help to maintain this lib I would like to add you as a collaborator. what do you think?

**Comment by joshterrill** [comment]
@webcat12345 We are using this in one of our products and need some things fixed for it. I've already fixed them locally and would like to push them up. Could you give me collaborator status on github so I can push fixes to github and NPM? I would rather just push the fixes up to this repo and help everyone out rather than fork the repo and upload my own.

**Comment by webcat12345** [comment]
@joshterrill i have added you as a collaborator. Let me give you npm access as well.

**Comment by webcat12345** [comment]
What is your npm account name @joshterrill ?

**Comment by joshterrill** [comment]
@webcat12345 my npm account is the same name. https://www.npmjs.com/~joshterrill

**Comment by pasevin** [comment]
I've updated this package to support Angular 7 with some additional features. Check it out.

**Comment by webcat12345** [comment]
Great, thanks @pasevin , I really want to open this repo to others to contribute together

**Comment by pasevin** [comment]
It's really hard to find a good, Angular package for phone validation. Before committing to this one, I checked all available ones. And this was the best IMHO. Worth continuing it!
