### ISSUE TITLE
How to differentiate phone numbers between countries, canada and usa seems to have same dial code. So a valid US number is being flagged to Canada flag?

### ISSUE THREAD

**Issue by imkiran** [webcat12345/ngx-intl-tel-input#154]

**Comment by pasevin** [comment]
Good point regarding the same dial code "+1"

**google-libphonenumber** library has a ```isValidNumberForRegion``` validation option, which if implemented in our library could solve this issue.

I've tested this on my build. @webcat12345 is there a specific reason you used ```isValidNumber(number)``` instead of ```isValidNumberForRegion(number, 'US')``` in ```ngx-intl-tel-input.validator.ts```?

If no, I could replace it and deploy.

**Comment by imkiran** [comment]
@pasevin @webcat12345 Even if you pass the country value to `isValidNumberForRegion(number, 'US')` you will still be getting the canada validated number value not the us number validation. Its because we are having dialCode 1 for four countries. It happens to pick the canada iso code since it is the first element in the array. I hope we should be dealing with areaCodes to pass this. 
<img width="734" alt="screen shot 2019-02-11 at 12 03 38 pm" src="https://user-images.githubusercontent.com/32508998/52548778-8f8b0180-2df5-11e9-9244-ee54266523c0.png">

**Comment by pasevin** [comment]
Oh, I understand now. You mean if I begin typing +1 415 ... it will automatically select Canadian flag instead of US. Is that right?

I was thinking this is about validation, but it's about the input behavior.

I'm currently swamped with work, so encourage anyone who has time to look into this.

I myself will look into this when I find the time. But no ETA.

**Comment by pasevin** [comment]
I looked into this quickly and I can see that the proper way would be to use ```this.phoneUtil.getRegionCodeForNumber(number)``` instead of what we do now.

BUT, it will identify and select the country only after the number has been entered fully.
Which is not ideal, but looks like there's no other built-in way.

I tested it on my build, and it works with US / CA differentiation.

So the only issue is that the flag will not change until the whole number is completed.

Is this acceptable? Any other ideas?

**Comment by imkiran** [comment]
No the flag should ideally change as user keeps typing. That will be the right user experience.

**Comment by pasevin** [comment]
Then I guess, it will take longer to come up with a custom solution, which matches ```areaCode``` if multiple ```dialCode``` found.

```nationalNumber``` starts with area code like so ```415...``` so probably it must happen here.

**Comment by imkiran** [comment]
Okay please let me know when we can have this fixed. It's a prime feature.

**Comment by pasevin** [comment]
Good news, I have a solution. Will push and publish tomorrow ;)

**Comment by imkiran** [comment]
Great you are awesome.

**Comment by imkiran** [comment]
This is ontario canada number `+1-613-555-0191` but  the flag is still `US`. I have set 'enableAutoCountrySelect' to `true`. Can you please check it. I will reopen the issue.
<img width="277" alt="screen shot 2019-02-12 at 12 20 30 pm" src="https://user-images.githubusercontent.com/32508998/52617126-cda12780-2ec0-11e9-8cf1-160a47dd1f52.png">
<img width="274" alt="screen shot 2019-02-12 at 12 20 38 pm" src="https://user-images.githubusercontent.com/32508998/52617128-cda12780-2ec0-11e9-9350-03db0efcedbb.png">
