### ISSUE TITLE
TooltipLabel import showing error

### ISSUE THREAD

**Issue by balaji-raj** [webcat12345/ngx-intl-tel-input#373]
Team, 

  Am getting this error related to angular 11 **export 'TooltipLabel' was not found in 'ngx-intl-tel-input**,

Please look my package.json.
![image](https://user-images.githubusercontent.com/16265223/112487195-8aedf100-8da2-11eb-9580-2c4652bad5a4.png)

**Comment by pasevin** [comment]
```TooltipLabel``` has been removed in the latest update. Ref: https://github.com/webcat12345/ngx-intl-tel-input/pull/336

**Comment by lightmare** [comment]
@pasevin Sorry for cross-posting, I was commenting on the PR around the same time you were closing this, and didn't notice the cross-reference there (not sure whether because the comments didn't refresh, or I just habitually skip over auto-generated stuff between comments). I would like to know why major version was not bumped after an export was removed.
